apiVersion: v1
kind: ConfigMap
metadata:
  name: camera-driver-config
  namespace: tafy-system
data:
  config.yaml: |
    device: /dev/video0
    node:
      type: "camera-usb"
    camera:
      width: 640
      height: 480
      fps: 30
      format: "MJPEG"
      quality: 85
    nats:
      url: nats://nats:4222
      name: camera-driver
    server:
      http_port: 8080
      metrics_port: 8081
      cors_origins: "*"
    log:
      level: info
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: camera-driver
  namespace: tafy-system
  labels:
    app: camera-driver
    component: driver
spec:
  selector:
    matchLabels:
      app: camera-driver
  template:
    metadata:
      labels:
        app: camera-driver
        component: driver
    spec:
      hostNetwork: true
      serviceAccountName: camera-driver
      containers:
      - name: camera-driver
        image: tafy/camera-usb:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: TAFY_CAMERA_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: dev
          mountPath: /dev
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 8081
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: camera-driver-config
      - name: dev
        hostPath:
          path: /dev
      nodeSelector:
        tafy.studio/camera: "true"
      tolerations:
      - key: "tafy.studio/edge"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: camera-driver
  namespace: tafy-system
---
apiVersion: v1
kind: Service
metadata:
  name: camera-driver
  namespace: tafy-system
  labels:
    app: camera-driver
spec:
  selector:
    app: camera-driver
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 8081
    targetPort: 8081
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: camera-driver
  namespace: tafy-system
spec:
  podSelector:
    matchLabels:
      app: camera-driver
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: tafy-system
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8081
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: tafy-system
    ports:
    - protocol: TCP
      port: 4222  # NATS
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53  # DNS
    - protocol: UDP
      port: 53