version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/apps/hub-ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/hub-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/apps/tafyd"
    schedule:
      interval: "weekly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Go
  - package-ecosystem: "gomod"
    directory: "/apps/tafyd"
    schedule:
      interval: "weekly"

  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/apps/hub-api"
    schedule:
      interval: "weekly"