version: '3.8'

services:
  # NATS messaging server
  nats:
    image: nats:latest
    container_name: tafy-nats
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
      - "6222:6222"  # Cluster
    command: [
      "-js",                # Enable JetStream
      "-sd", "/data",       # Storage directory
      "-m", "8222",         # HTTP monitoring port
      "--name", "tafy-nats" # Server name
    ]
    volumes:
      - nats-data:/data
    networks:
      - tafy-net

  # PostgreSQL for device registry (optional, can use NATS KV instead)
  postgres:
    image: postgres:15-alpine
    container_name: tafy-postgres
    environment:
      POSTGRES_USER: tafy
      POSTGRES_PASSWORD: tafy-dev
      POSTGRES_DB: tafy_studio
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tafy-net

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: tafy-redis
    ports:
      - "6379:6379"
    networks:
      - tafy-net

  # Node-RED for flow programming
  node-red:
    image: nodered/node-red:latest
    container_name: tafy-node-red
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    environment:
      - TZ=UTC
    networks:
      - tafy-net
    depends_on:
      - nats

  # Traefik reverse proxy
  traefik:
    image: traefik:v3.0
    container_name: tafy-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - tafy-net

volumes:
  nats-data:
  postgres-data:
  node-red-data:

networks:
  tafy-net:
    driver: bridge