name: Documentation

on:
  push:
    branches: [main, develop]
    paths:
      - 'docs/**'
      - 'README.md'
      - '**/*.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - '**/*.md'
      - '.github/workflows/docs.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
        
      - name: Lint Markdown files
        run: |
          markdownlint '**/*.md' \
            --ignore node_modules \
            --ignore .venv \
            --ignore '**/node_modules/**' \
            --ignore '**/dist/**' \
            --ignore '**/.next/**'

  check-links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: |
            --verbose 
            --no-progress 
            --accept 200,204,206 
            --timeout 20 
            --max-retries 3 
            --exclude-all-private 
            --exclude 'localhost' 
            --exclude '127.0.0.1' 
            --exclude 'example.com' 
            --exclude 'tafy.local' 
            --exclude-path .venv 
            --exclude-path node_modules 
            --exclude-path .next 
            --exclude-path dist 
            docs/**/*.md README.md
          fail: true

  check-spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check spelling
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: |
            **/*.md
            **/*.ts
            **/*.tsx
            **/*.js
            **/*.jsx
            **/*.py
            **/*.go
          exclude: |
            node_modules/**
            .venv/**
            dist/**
            .next/**
            **/node_modules/**
            **/.venv/**
            **/dist/**
            **/.next/**
            pnpm-lock.yaml
            uv.lock
            go.sum

  validate-structure:
    name: Validate Documentation Structure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check required documentation files
        run: |
          echo "Checking for required documentation files..."
          required_files=(
            "README.md"
            "docs/VISION.md"
            "docs/ARCHITECTURE.md"
            "docs/CONCEPTS.md"
            "docs/DEVELOPMENT_SETUP.md"
            "docs/TESTING.md"
            "docs/SECURITY.md"
          )
          
          missing_files=()
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              missing_files+=("$file")
            fi
          done
          
          if [ ${#missing_files[@]} -ne 0 ]; then
            echo "❌ Missing required documentation files:"
            printf '%s\n' "${missing_files[@]}"
            exit 1
          else
            echo "✅ All required documentation files present"
          fi
      
      - name: Check documentation completeness
        run: |
          echo "Checking for TODO items in documentation..."
          if grep -r "TODO\|FIXME\|XXX" docs/ README.md --include="*.md"; then
            echo "⚠️  Found TODO items in documentation - these should be addressed"
            # Don't fail the build, just warn
          else
            echo "✅ No TODO items found in documentation"
          fi


  summary:
    name: Documentation Summary
    runs-on: ubuntu-latest
    if: always()
    needs: [lint-markdown, check-links, check-spelling, validate-structure]
    steps:
      - name: Summary
        run: |
          echo "## Documentation Check Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.lint-markdown.result }}" == "success" ]; then
            echo "✅ Markdown linting passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Markdown linting failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.check-links.result }}" == "success" ]; then
            echo "✅ Link checking passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Link checking failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.check-spelling.result }}" == "success" ]; then
            echo "✅ Spell checking passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Spell checking failed" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.validate-structure.result }}" == "success" ]; then
            echo "✅ Documentation structure validated" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Documentation structure validation failed" >> $GITHUB_STEP_SUMMARY
          fi