# This workflow triggers a documentation build in the tafystudio-docs repository
# whenever documentation files are updated in this repository

name: Trigger Documentation Build

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - '**/*.md'
      - 'Makefile'
      - 'scripts/extract-docs.sh'
      - 'packages/**/package.json'
      - 'apps/**/pyproject.toml'
      - 'apps/**/go.mod'
      - '.github/workflows/trigger-docs-build.yml'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Validate documentation
        run: |
          echo "Validating documentation structure..."
          # Check required documentation files exist
          for file in docs/VISION.md docs/ARCHITECTURE.md docs/CONCEPTS.md docs/QUICKSTART.md; do
            if [ ! -f "$file" ]; then
              echo "ERROR: Required file $file not found"
              exit 1
            fi
          done
          echo "Documentation validation passed"
      
      - name: Trigger docs repository build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DOCS_TRIGGER_TOKEN }}
          repository: tafystudio/tafystudio-docs
          event-type: docs-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
