# This workflow triggers a documentation build in the tafystudio-docs repository
# whenever documentation files are updated in this repository

name: Trigger Documentation Build

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'CLAUDE.md'
      - 'packages/*/README.md'
      - 'apps/*/README.md'
      - '.github/workflows/trigger-docs-build.yml'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs repository build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DOCS_TRIGGER_TOKEN }}
          repository: tafystudio/tafystudio-docs
          event-type: docs-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
